name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL_CODE_TIME: 'True'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_COMMIT: 'False'
          SHOW_DAYS_OF_WEEK: 'False'
          SHOW_LANGUAGE: 'True'
          SHOW_TIMEZONE: 'False'
          SHOW_EDITORS: 'False'
          SHOW_OS: 'False'
          SHOW_PROJECTS: 'False'
          SHOW_LINES_OF_CODE: 'False'
          SHOW_LOC_CHART: 'False'
          SHOW_SHORT_INFO: 'False'
